name: BVT
on: [pull_request]
jobs:
  check:
    name: Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [uipath-ubuntu-latest, macos-latest, uipath-windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26  # v3.7.0
      - name: Check
        run: |
          make check-all

  make:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [uipath-ubuntu-latest, macos-latest, uipath-windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26  # v3.7.0
      - name: Build
        run: |
          make
          make -C compiler
          make -C ttrpc-codegen
          make -C example build-examples

  deny:
    runs-on: uipath-ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans sources

    # Prevent sudden announcement of a new advisory from failing ci:
    continue-on-error: ${{ matrix.checks == 'advisories' }}

    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26  # v3.7.0
      - uses: EmbarkStudios/cargo-deny-action@3f4a782664881cf5725d0ffd23969fcce89fd868  # v1.6.3
        with:
          command: check ${{ matrix.checks }}
